### ISSUE TITLE
How can I parse ISO 8601 / RFC 3339 datetime string and format in browser's timezone?

### ISSUE THREAD

**Issue by Boscop** [awakesecurity/purescript-precise-datetime#12]
How can I parse a ISO 8601 / RFC 3339 datetime string and format it in the browser's timezone? (or a given timezone)

Thanks :)

**Comment by paulyoung** [comment]
We're mostly deferring to [`purescript-datetime`](https://github.com/purescript/purescript-datetime) for dealing with locales.

Here's the output of a quick `pulp repl` session that defines and uses a few locales.

```purescript
import Prelude
> import Data.DateTime.Locale
> import Data.Maybe
> import Data.PreciseDateTime.Locale (toRFC3339String)
> import Data.PreciseDateTime (fromRFC3339String)
> import Data.RFC3339String
> import Data.Time.Duration as Duration
```

```purescript
> pst = Locale (Just $ LocaleName "PST") (Duration.Minutes $ -8.0 * 60.0)
> pdt = Locale (Just $ LocaleName "PDT") (Duration.Minutes $ -7.0 * 60.0)
> utc = (Just $ LocaleName "UTC") (Duration.Minutes 0.0)
> precDateTime = fromRFC3339String $ RFC3339String "2018-03-07T18:21:10.123456789Z"
```

```purescript
> LocalValue pst <$> precDateTime
(Just (LocalValue (Locale (Just (LocaleName "PST")) (Minutes -480.0)) PreciseDateTime ((DateTime (Date (Year 2018) March (Day 7)) (Time (Hour 18) (Minute 21) (Second 10) (Millisecond 123)))) (Nanosecond 123456789)))
> toRFC3339String <<< LocalValue pst <$> precDateTime
(Just (RFC3339String "2018-03-07T18:21:10.123456789-08:00"))
```

```purescript
> LocalValue pdt <$> precDateTime
(Just (LocalValue (Locale (Just (LocaleName "PDT")) (Minutes -420.0)) PreciseDateTime ((DateTime (Date (Year 2018) March (Day 7)) (Time (Hour 18) (Minute 21) (Second 10) (Millisecond 123)))) (Nanosecond 123456789)))
> toRFC3339String <<< LocalValue pdt <$> precDateTime
(Just (RFC3339String "2018-03-07T18:21:10.123456789-07:00"))
```

```purescript
> LocalValue utc <$> precDateTime
(Just (LocalValue (Locale (Just (LocaleName "UTC")) (Minutes 0.0)) PreciseDateTime ((DateTime (Date (Year 2018) March (Day 7)) (Time (Hour 18) (Minute 21) (Second 10) (Millisecond 123)))) (Nanosecond 123456789)))
> toRFC3339String <<< LocalValue utc <$> precDateTime
(Just (RFC3339String "2018-03-07T18:21:10.123456789Z"))
```

I'm not sure about how to get the browsers' locale but maybe [`purescript-js-date`](https://github.com/purescript-contrib/purescript-js-date) can help with that.

**Comment by themattchan** [comment]
If you call javascript's `Date.toString()` it will format the date in your browser's timezone. I think this function is exported somewhere in `purescript-datetime`.

**Comment by Boscop** [comment]
@paulyoung But how does that work with CET which sometimes has a daylight savings time? Do I have to manually compute if DST is active now and then apply the offset conditionally? Or is there support for this already?

**Comment by paulyoung** [comment]
@Boscop we're leveraging much of what `purescript-datetime` offers, and since it provides no built-in support for such things <sup>[1](https://github.com/purescript/purescript-datetime#documentation)</sup>, we also defer to other libraries for this sort of thing.

I think you would need to know if DST is active and do something like this:

```purescript
cet = Locale (Just $ LocaleName "CET") (Duration.Minutes $ 1.0 * 60.0)
cetDst = Locale (Just $ LocaleName "CET DST") (Duration.Minutes $ 2.0 * 60.0)
```

**Comment by Boscop** [comment]
@themattchan Thanks, but I want to convert the timezone before doing custom (german) formatting. This is my current function which is wrong because it doesn't convert the timezone from utc to browser local / german:
```haskell
fmt_rfc3339 = parseFormatString "YYYY-MM-DDTHH:mm:ss+00:00"
fmt_german = parseFormatString "DD.MM.YYYY, HH:mm"

humanTime s = either id id do
  decode <- fmt_rfc3339
  encode <- fmt_german
  datetime <- unformat decode s
  pure $ format encode datetime
```
And it also fails when the datetime string is valid rfc3339 but not matching the format string I'm using (e.g. if it has microseconds or a different timezone)..

@paulyoung 
1. Thanks. I have a question: In your first reply, why did you use `Locale` for `pdt` but not `utc`?
```haskell
> pdt = Locale (Just $ LocaleName "PDT") (Duration.Minutes $ -7.0 * 60.0)
> utc = (Just $ LocaleName "UTC") (Duration.Minutes 0.0)
```
2.  Looking at [this](https://stackoverflow.com/a/1091399/7488353) it should be possible to use that in PS, right?
In my browser (CET) it returns `-60`.
So can I use that in PS like this?:
```haskell
now = ? -- PureScript equivalent of `new Date()`
utcOffset = getTimezoneOffset now
browserLocale = Locale (Just $ LocaleName "browser") (Duration.Minutes utcOffset)
precDateTime = fromRFC3339String $ RFC3339String "2018-03-07T18:21:10.123456789Z"
timeAslocal = LocalValue browserLocale <$> precDateTime
-- now format `timeAslocal` as "DD.MM.YYYY, HH:mm"
```
But what's the PureScript equivalent of `new Date()`?
And how can I then format `timeAslocal` as `"DD.MM.YYYY, HH:mm"`?
