### ISSUE TITLE
Provide smart constructors for PreciseDateTime

### ISSUE THREAD

**Issue by natefaubion** [awakesecurity/purescript-precise-datetime#9]
`Nanoseconds` is bound to 1s, but `DateTime` is precise up to the millisecond, so the ns component should never be equal to or greater than 1ms. We should provide smart constructors instead of exposing the representation that account for any inconsistency.

**Comment by paulyoung** [comment]
@themattchan is using the constructor but also just proposed using a smart constructor instead.

**Comment by themattchan** [comment]
Something like `mkPreciseDateTime :: Date -> Hour -> Minute -> Second -> Nanosecond -> PreciseDateTime`?

I'd argue against `mkPreciseDateTime :: DateTime -> Nanosecond -> PreciseDateTime` as one would expect the following to hold:

```
toDateTime (mkPreciseDateTime dateTime ns) == dateTime
```

but in the second version we will have to potentially modify the milliseconds in `DateTime` to make it agree with the nanoseconds.

**Comment by paulyoung** [comment]
Good point.
